import type { Metadata, Viewport } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";
import Footer from "@/components/Footer";
import JsonLd from "@/components/JsonLd";
import { QuoteProvider } from "@/components/quote/QuoteContext";
import QuoteBar from "@/components/quote/QuoteBar";
import { organizationJsonLd, localBusinessJsonLd } from "@/lib/seo";
import { SITE, KEYWORDS } from "@/lib/site";

const inter = Inter({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-inter",
});

export const viewport: Viewport = {
  themeColor: "#166534",
  width: "device-width",
  initialScale: 1,
};

// Site-wide metadata defaults. Page-level metadata overrides title/description.
export const metadata: Metadata = {
  metadataBase: new URL(SITE.url),
  title: {
    default: `${SITE.name} | Farm Manure & Agricultural Equipment Supplier`,
    template: `%s | ${SITE.name}`,
  },
  description: SITE.description,
  keywords: KEYWORDS,
  authors: [{ name: SITE.owner }],
  creator: SITE.owner,
  publisher: SITE.name,
  applicationName: SITE.name,
  category: "Agriculture",
  robots: {
    index: true,
    follow: true,
    googleBot: {
      index: true,
      follow: true,
      "max-image-preview": "large",
      "max-snippet": -1,
      "max-video-preview": -1,
    },
  },
  openGraph: {
    type: "website",
    locale: "en_US",
    url: SITE.url,
    siteName: SITE.name,
    title: `${SITE.name} | Farm Manure & Agricultural Equipment`,
    description: SITE.description,
    // OG/Twitter images are generated by app/opengraph-image.tsx (file convention).
  },
  twitter: {
    card: "summary_large_image",
    title: `${SITE.name} | Farm Manure & Agricultural Equipment`,
    description: SITE.shortDescription,
    creator: SITE.twitterHandle,
  },
  icons: {
    icon: [{ url: "/favicon.svg", type: "image/svg+xml" }],
    apple: "/favicon.svg",
  },
  formatDetection: { telephone: true, address: true, email: true },
  // Set NEXT_PUBLIC_GOOGLE_SITE_VERIFICATION in .env.local to emit the
  // Google Search Console verification meta tag.
  ...(process.env.NEXT_PUBLIC_GOOGLE_SITE_VERIFICATION
    ? {
        verification: {
          google: process.env.NEXT_PUBLIC_GOOGLE_SITE_VERIFICATION,
        },
      }
    : {}),
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={inter.variable}>
      <body>
        <JsonLd data={[organizationJsonLd(), localBusinessJsonLd()]} />
        <QuoteProvider>
          <Header />
          <main id="main">{children}</main>
          <Footer />
          <QuoteBar />
        </QuoteProvider>
      </body>
    </html>
  );
}
